### ISSUE TITLE
Large raster upscaling uint64 index bug in upscale.py/ihu_relocate_outlets

### ISSUE THREAD

**Issue by sasjabs** [Deltares/pyflwdir#79]
### pyFlwDir version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of pyFlwDir.

### Reproducible Example

I'm trying to upscale a very large flow direction raster (HydroSHEDS 3 arc-second Africa, 96000x96000 resolution, 9.2 billion cells):
```python
import rasterio
import pyflwdir
import numpy as np


with rasterio.open(r"data\flowdir\reference\af_dir_3s\af_dir_3s.tif") as src:
    flwdir_arr = src.read(1)
    transform = src.transform
    crs = src.crs
    profile = src.profile
    nodata = src.nodata

with rasterio.open(r"data\flowacc\reference\af_acc_3s\af_acc_3s.tif") as src:
    uparea = src.read(1, out_dtype=np.uint32)
    
flw = pyflwdir.from_array(
    flwdir_arr,
    ftype="d8", 
    transform=transform,
    latlon=crs.is_geographic,
    cache=True
)

scale_factor = 10
flw_lowres, idxs_out = flw.upscale(
    scale_factor=scale_factor,
    uparea=uparea,
    method="ihu"
)
```

### Current behaviour

I'm getting this error traceback
```
Traceback (most recent call last):
  File "C:\Users\penrunner\Desktop\fdcomp\ihu_test_cont.py", line 32, in <module>
    flw_lowres, idxs_out = flw.upscale(
                           ^^^^^^^^^^^^
  File "C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\pyflwdir.py", line 1038, in upscale
    idxs_ds1, idxs_out, shape1 = getattr(upscale, method)(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py", line 1250, in ihu
    idxs_ds, subidxs_out, idxs_fix1 = ihu_relocate_outlets(
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\numba\core\dispatcher.py", line 424, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\numba\core\dispatcher.py", line 365, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(array(uint64, 1d, C), float64)

There are 22 candidate implementations:
 - Of which 20 did not match due to:
 Overload of function 'getitem': File: <numerous>: Line N/A.
   With argument(s): '(array(uint64, 1d, C), float64)':
  No match.
 - Of which 2 did not match due to:
 Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 211.
   With argument(s): '(array(uint64, 1d, C), float64)':
  Rejected as the implementation raised a specific error:
    NumbaTypeError: Unsupported array index type float64 in [float64]
  raised from C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\numba\core\typing\arraydecl.py:104

During: typing of intrinsic-call at C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py (733)
During: typing of intrinsic-call at C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py (734)
During: typing of intrinsic-call at C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py (823)
During: typing of intrinsic-call at C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py (824)
During: typing of intrinsic-call at C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py (829)
During: typing of intrinsic-call at C:\Users\penrunner\Desktop\fdcomp\venv\Lib\site-packages\pyflwdir\upscale.py (832)

File "venv\Lib\site-packages\pyflwdir\upscale.py", line 733:
def ihu_relocate_outlets(
    <source elided>
                    # update MAIN connection
                    if idxs_ds[idx0] != idx1:
                    ^

During: Pass nopython_type_inference
Error in sys.excepthook:

Original exception was:
```

### Desired behaviour

Returns upscaled flow direction array

### Additional context

I've tried to solve this issue with Claude Opus, it figured this:

> The problem is not about the dtype of your upstream area array. It's a bug in pyflwdir's handling of very large rasters, triggered by the dtype it selects for internal index arrays.
The key line is in pyflwdir.py:
``` python
# use smallest possible dtype to represent indices    
n = data.size    
dtype = np.int32 if n < 2147483647 else (np.uint32 if n < 4294967294 else np.uint64)
```

> Your Africa 3-arc-second raster (af_dir_3s) has roughly 9.2 billion cells, which exceeds 4,294,967,294. So pyflwdir selects np.uint64 for idxs_ds (and all derived index arrays like subidxs_out, idxs_fix, etc.).
The problem then manifests inside the Numba-compiled upscale functions. For example, in ihu_relocate_outlets, the variable idx0 gets assigned values from two sources with incompatible types:
uint64 — from indexing uint64 arrays, e.g. idx0 = idx00 where idx00 = idxs_fix1[i0] (line 578/692)
int64 — from subidx_2_idx() which performs integer arithmetic returning int64 (line 588, 612)
When Numba's type inference needs to unify uint64 and int64 for the same variable, it cannot find an integer type that encompasses both ranges (uint64 goes up to 2^64-1, int64 goes down to -2^63). So Numba promotes the variable to float64. Then, when that float64 variable is used as an array index (idxs_ds[idx0]), Numba fails because float64 indexing is not supported.
This explains why it works on smaller datasets — with < 2.1 billion cells, int32 is used, which cleanly promotes to int64 without conflict.

The AI suggested that a quick fix for me would be to change [pyflwdir.py, line 167](https://github.com/Deltares/pyflwdir/blob/1221a9fd5174da9c1d305fab8cd5421ff7156028/pyflwdir/pyflwdir.py#L167C1-L167C89) from:
```
dtype = np.int32 if n < 2147483647 else (np.uint32 if n < 4294967294 else np.uint64)
```
to:
```
dtype = np.int32 if n < 2147483647 else np.int64
```
And this worked.

Seems like the problem is specifically with uint64 dtype for array indices in [upscale.py/ihu_relocate_outlets](https://github.com/Deltares/pyflwdir/blob/1221a9fd5174da9c1d305fab8cd5421ff7156028/pyflwdir/upscale.py#L523). The case with 15 arc-second global raster (~2.9 billion cells, so uint32 dtype is selected) works just fine.

I'm not really sure if Claude's explanation is correct and I'm really not sure that this is the best way to fix this issue. Anyway, it worked for me as a quick fix.

**Comment by DirkEilander** [comment]
Thanks for raising this issue and your detailed description. It seems to be related to the initialization of list with the wrong dtype by numba. I need to investigate the issue a bit further.

The claude solution is not a good fix as it actually limits the maximum array size.
